#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

BASE_URL="${SEATUNNELX_BASE_URL:-${1:-http://127.0.0.1:8801}}"
PROM_SD_PATH="${OBS_PROM_SD_PATH:-/api/v1/monitoring/prometheus/discovery}"
ALERT_WEBHOOK_PATH="${OBS_ALERT_WEBHOOK_PATH:-/api/v1/monitoring/alertmanager/webhook}"

COOKIE_JAR="$(mktemp)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR" "$COOKIE_JAR"' EXIT

join_url() {
  local path="$1"
  if [[ "$path" =~ ^https?:// ]]; then
    echo "$path"
    return
  fi
  if [[ "$path" == /* ]]; then
    echo "${BASE_URL%/}${path}"
    return
  fi
  echo "${BASE_URL%/}/$path"
}

request_json() {
  local name="$1"
  local method="$2"
  local url="$3"
  local body="${4:-}"
  local outfile="$TMP_DIR/${name}.json"
  local code

  if [[ -n "$body" ]]; then
    code="$(curl -sS -o "$outfile" -w '%{http_code}' -X "$method" "$url" \
      -H 'Content-Type: application/json' \
      -b "$COOKIE_JAR" -c "$COOKIE_JAR" \
      --data "$body")"
  else
    code="$(curl -sS -o "$outfile" -w '%{http_code}' -X "$method" "$url" \
      -b "$COOKIE_JAR" -c "$COOKIE_JAR")"
  fi

  echo "[$name] $method $url -> HTTP $code"
  if [[ "$code" -ge 400 ]]; then
    cat "$outfile"
    echo
    return 1
  fi

  head -c 500 "$outfile"
  echo
  echo
}

echo "SeaTunnelX base URL: $BASE_URL"

# 1) Prometheus HTTP SD
request_json "prometheus_discovery" "GET" "$(join_url "$PROM_SD_PATH")"

# 2) Alertmanager webhook ingest (public endpoint)
STARTS_AT="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
ENDS_AT="$(date -u -d '+5 minutes' +'%Y-%m-%dT%H:%M:%SZ')"
read -r -d '' WEBHOOK_PAYLOAD <<JSON || true
{
  "receiver": "seatunnelx",
  "status": "firing",
  "commonLabels": {
    "cluster_id": "1",
    "cluster_name": "smoke-cluster",
    "env": "smoke"
  },
  "commonAnnotations": {
    "summary": "smoke test alert"
  },
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "SeaTunnelSmokeAlert",
        "severity": "warning",
        "cluster_id": "1",
        "cluster_name": "smoke-cluster",
        "env": "smoke"
      },
      "annotations": {
        "summary": "smoke test alert",
        "description": "generated by scripts/observability-remote-smoke.sh"
      },
      "startsAt": "$STARTS_AT",
      "endsAt": "$ENDS_AT",
      "generatorURL": "$BASE_URL/smoke"
    }
  ]
}
JSON
request_json "alertmanager_webhook" "POST" "$(join_url "$ALERT_WEBHOOK_PATH")" "$WEBHOOK_PAYLOAD"

# 3) Authenticated APIs (optional)
if [[ -n "${SEATUNNELX_USERNAME:-}" && -n "${SEATUNNELX_PASSWORD:-}" ]]; then
  echo "Login with SEATUNNELX_USERNAME for authenticated API smoke checks..."
  read -r -d '' LOGIN_PAYLOAD <<JSON || true
{
  "username": "${SEATUNNELX_USERNAME}",
  "password": "${SEATUNNELX_PASSWORD}"
}
JSON
  request_json "auth_login" "POST" "$(join_url '/api/v1/auth/login')" "$LOGIN_PAYLOAD"

  request_json "remote_alerts" "GET" "$(join_url '/api/v1/monitoring/remote-alerts?page=1&page_size=5')"
  request_json "clusters_health" "GET" "$(join_url '/api/v1/clusters/health')"
  request_json "platform_health" "GET" "$(join_url '/api/v1/monitoring/platform-health')"
else
  echo "Skip authenticated API checks (set SEATUNNELX_USERNAME/SEATUNNELX_PASSWORD to enable)."
fi

echo "Remote observability smoke checks passed."
